apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: lobsters
  name: lobsters
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: lobsters
    spec:
      containers:
        - name: lobsters
        image: "myfolder/lobsters:2.0.0"
        env:
          - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: lobsters
              key: database-url
        ports:
          - name: http
          containerPort: 3000
          protocol: TCP
        resources:
          request:
            cpu: 0.5
            memory: 200M
          limites:
            cpu: 0.5
            memory: 200M
